#!/bin/csh


\rm .gmt*
gmtset MEASURE_UNIT INCH
gmtset ANOT_FONT_SIZE 6
gmtset LABEL_FONT_SIZE 6
gmtset COLOR_NAN  200/200/200

set pfad = `pwd`
set x0 = `awk '{print $1}' for.header`
set x1 = `awk '{print $2}' for.header`
set z0 = `awk '{print $5}' for.header`
set z1 = `awk '{print $6}' for.header`
set nx = `awk '{print $1}' inv.header`
set nz = `awk '{print $3}' inv.header`

set pal = col.cpt

grd2cpt x4.grd -Z -Crainbow >! $pal


# prepare topo file
awk '{if ($6==1)  print $1,$3 }' fd????.asc | sort -n | awk '{if (old!=$1) print $0; old=$1}' | sample1d -I0.1 >! rp.dat
awk '{if ($6==-1) print $1,$3 }' fd????.asc | sort -n >! sp.dat

set xmin = `awk '{print $1}' for.header`
set xmax = `awk '{print $2}' for.header`
set zmin = `awk '{print $5}' for.header`
set zmax = `awk '{print $6}' for.header`

echo $xmin $zmin >! elev.dat
echo $xmin `head -1 rp.dat | awk '{print $2}'` >> elev.dat
cat rp.dat >> elev.dat
echo $xmax `tail -1 rp.dat | awk '{print $2}'` >> elev.dat
echo $xmax $zmin >> elev.dat


grdimage x4.grd -JX-7/-1.717 -R$x0/$x1/$z0/$z1 -C$pal -B50f10/2f1SEW -V -K -Y1.25 -X0.75 -P >! x.ps
psxy elev.dat -JX -B -R -W1 -G255 -K -O >> x.ps
psxy rp.dat -JX -R -B -Sc0.01 -G0 -K -O >> x.ps
psxy sp.dat -JX -R -B -Sc0.02 -G255/0/0 -K -O >> x.ps
set dt = `egrep RMS log_4 | tail -1 | awk '{printf"DT = %8.1f ms\n", $7}'`
set dp = `egrep RMS log_4 | tail -1 | awk '{printf"%8d picks\n", $5}'`
echo  20 2 10 0 1 1 $dt | pstext -JX -R -N -O -K >> x.ps
echo 100 2 10 0 1 1 $pfad | pstext -JX -R -N -O -K >> x.ps
echo 100 2.4 10 0 1 1 $dp | pstext -JX -R -N -O -K >> x.ps

psscale -C$pal -D4/-0.5/6/0.1h -O -K >> x.ps


grdimage x3.grd -JX  -R -C$pal -B -V -K -O -Y2  >> x.ps
#psxy elev.dat -JX -B -R -W1 -G255 -K -O >> x.ps
psxy rp.dat -JX -R -B -Sc0.01 -G0 -K -O >> x.ps
psxy sp.dat -JX -R -B -Sc0.02  -G255/0/0 -K -O >> x.ps
set dt = `egrep RMS log_3 | tail -1 | awk '{printf"DT = %8.1f ms\n", $7}'`
echo  20 2 10 0 1 1 $dt | pstext -JX -R -N -O -K >> x.ps
#grdcontour x3.grd -Cvel.con -JX -K -O >> x.ps   


grdimage x2.grd -JX  -R -C$pal -B -V -K -O -Y2  >> x.ps
#psxy elev.dat -JX -B -R -W1 -G255 -K -O >> x.ps
psxy rp.dat -JX -R -B -Sc0.01 -G0 -K -O >> x.ps
psxy sp.dat -JX -R -B -Sc0.02  -G255/0/0 -K -O >> x.ps
set dt = `egrep RMS log_2 | tail -1 | awk '{printf"DT = %8.1f ms\n", $7}'`
echo  20 2 10 0 1 1 $dt | pstext -JX -R -N -O -K >> x.ps
#grdcontour x2.grd -Cvel.con -JX -K -O >> x.ps   


grdimage x1.grd -JX  -R -C$pal -B -V -K -O -Y2  >> x.ps
#psxy elev.dat -JX -B -R -W1 -G255 -K -O >> x.ps
psxy rp.dat -JX -R -B -Sc0.01 -G0 -K -O >> x.ps
psxy sp.dat -JX -R -B -Sc0.02  -G255/0/0 -K -O >> x.ps
set dt = `egrep RMS log_1 | tail -1 | awk '{printf"DT = %8.1f ms\n", $7}'`
echo  20 2 10 0 1 1 $dt | pstext -JX -R -N -O -K >> x.ps
#grdcontour x1.grd -Cvel.con -JX -K -O >> x.ps   


grdimage x0.grd -JX  -R -C$pal -B -V -K -O -Y2  >> x.ps
#psxy elev.dat -JX -B -R -W1 -G255 -K -O >> x.ps
psxy rp.dat -JX -R -B -Sc0.01 -G0 -K -O >> x.ps
psxy sp.dat -JX -R -B -Sc0.02  -G255/0/0 -K -O >> x.ps
set dt = `egrep RMS log_0 | tail -1 | awk '{printf"DT = %8.1f ms\n", $7}'`
echo  20 2 10 0 1 1 $dt | pstext -JX -R -N -O -K >> x.ps


echo 0 0 | psxy -JX -R -Si0.0001 -G0 -O  >> x.ps

